variables:
  ORD_SOUMET_SHELL: "/bin/bash"
  ORD_SOUMET_CPUS: "40"
  ORD_SOUMET_TMPFS: "8G"
  ORD_SOUMET_M: "80G"
  ORD_SOUMET_W: "30"
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - run_configs_gnu
  - run_configs_intel

before_script:
  - export CLICOLOR_FORCE=1

# U2 GNU 9.3.0 with oneAPI
build_gnu-9.3.0:
  stage: build
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_gnu
    - . ./.initial_setup
    - make cmake
    - make -j `nproc`
    - make -j `nproc` work
  allow_failure: true

# U2 GNU 12.1.0 with OpenMPI
build_gnu-12.1.0:
  stage: build
  when: always
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_gnu_12
    - . ./.initial_setup
    - ln -sf  ${ECCI_DATA_DIR}/gem_dbase .
    - make cmake
    - make -j `nproc`
    - make work
  artifacts:
    expire_in: 2 hrs
    paths:
    - work-rhel-8-icelake-64-gnu-12.1.0
    - gem_dbase

# U2 Intel 2022
build_intel:
  stage: build
  when: always
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_intel
    - . ./.initial_setup
    - ln -sf  ${ECCI_DATA_DIR}/gem_dbase .
    - make cmake
    - make -j `nproc`
    - make -j `nproc` work
  artifacts:
    expire_in: 2 hrs
    paths:
    - work-rhel-8-icelake-64-intel-2021.5.0
    - gem_dbase

5.2GEM_GY_FISL_H_intel:
  stage: run_configs_intel
  dependencies:
  - build_intel
  when: always
  only:
  - tags
  allow_failure: true
  script:
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_intel
    - cd $GEM_WORK
    - CFG=5.2GEM_cfgs_GY_FISL_H
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo;
      fi
    - test "${_status}" == "ED"

CANO_W7cascP_intel:
  stage: run_configs_intel
  dependencies:
  - build_intel
  when: always
  allow_failure: true
  only:
  - tags
  script:
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_intel
    - cd $GEM_WORK
    - CFG=CANO_cfgs_W7cascP
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo;
      fi
    - test "${_status}" == "ED"

CANO_dcmip163r100_intel:
  stage: run_configs_intel
  dependencies:
  - build_intel
  when: always
  only:
  - tags
  allow_failure: true
  script:
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_intel
    - cd $GEM_WORK
    - CFG=CANO_cfgs_dcmip163r100
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo;
      fi
    - test "${_status}" == "ED"

CANO_wil7_intel:
  stage: run_configs_intel
  dependencies:
  - build_intel
  when: always
  only:
  - tags
  allow_failure: true
  script:
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_intel
    - cd $GEM_WORK
    - CFG=CANO_cfgs_wil7
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo;
      fi
    - test "${_status}" == "ED"

GEM_cfgs_intel:
  stage: run_configs_intel
  dependencies:
  - build_intel
  when: always
  only:
  - tags
  allow_failure: true
  script:
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_intel
    - cd $GEM_WORK
    - CFG=GEM_cfgs
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo;
      fi
    - test "${_status}" == "ED"

GEM_GY_FISL_P_intel:
  stage: run_configs_intel
  dependencies:
  - build_intel
  when: always
  only:
  - tags
  allow_failure: true
  script:
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_intel
    - cd $GEM_WORK
    - CFG=GEM_cfgs_GY_FISL_P
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo;
      fi
    - test "${_status}" == "ED"

GEM_GY_FISL_H_intel:
  stage: run_configs_intel
  dependencies:
  - build_intel
  when: always
  only:
  - tags
  allow_failure: true
  script:
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_intel
    - cd $GEM_WORK
    - CFG=GEM_cfgs_GY_FISL_H
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo;
      fi
    - test "${_status}" == "ED"

GEM_LU_FISL_H_intel:
  stage: run_configs_intel
  dependencies:
  - build_intel
  when: always
  only:
  - tags
  allow_failure: true
  script:
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_intel
    - cd $GEM_WORK
    - CFG=GEM_cfgs_LU_FISL_H
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo;
      fi
    - test "${_status}" == "ED"

GEM_LU_OFFC_intel:
  stage: run_configs_intel
  dependencies:
  - build_intel
  when: always
  only:
  - tags
  allow_failure: true
  script:
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_intel
    - cd $GEM_WORK
    - CFG=GEM_cfgs_LU_OFFC
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo;
      fi
    - test "${_status}" == "ED"

PTOPO_GYH_intel:
  stage: run_configs_intel
  dependencies:
  - build_intel
  when: always
  only:
  - tags
  allow_failure: true
  script:
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_intel
    - cd $GEM_WORK
    - CFG=PTOPO_cfgs_GYH
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo;
      fi
    - test "${_status}" == "ED"

PTOPO_LUP_intel:
  stage: run_configs_intel
  dependencies:
  - build_intel
  when: always
  only:
  - tags
  allow_failure: true
  script:
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_intel
    - cd $GEM_WORK
    - CFG=PTOPO_cfgs_LUP
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo;
      fi
    - test "${_status}" == "ED"

RSTRT_GYP_intel:
  stage: run_configs_intel
  dependencies:
  - build_intel
  when: always
  only:
  - tags
  allow_failure: true
  script:
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_intel
    - cd $GEM_WORK
    - CFG=RSTRT_cfgs_GYP
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo;
      fi
    - test "${_status}" == "ED"

THEO_bubbleG_intel:
  stage: run_configs_intel
  dependencies:
  - build_intel
  when: always
  only:
  - tags
  allow_failure: true
  script:
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_intel
    - cd $GEM_WORK
    - CFG=THEO_cfgs_bubbleG
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo;
    - test "${_status}" == "ED"

THEO_schar_intel:
  stage: run_configs_intel
  dependencies:
  - build_intel
  when: always
  only:
  - tags
  allow_failure: true
  script:
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_intel
    - cd $GEM_WORK
    - CFG=THEO_cfgs_schar
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo;
    - test "${_status}" == "ED"

5.2GEM_GY_FISL_H_gnu:
  stage: run_configs_gnu
  dependencies:
  - build_gnu-12.1.0
  when: always
  only:
  - tags
  allow_failure: true
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_gnu_12
    - cd $GEM_WORK
    - CFG=5.2GEM_cfgs_GY_FISL_H
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo;
      fi
    - test "${_status}" == "ED"

CANO_W7cascP_gnu:
  stage: run_configs_gnu
  dependencies:
  - build_gnu-12.1.0
  when: always
  only:
  - tags
  allow_failure: true
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_gnu_12
    - cd $GEM_WORK
    - CFG=CANO_cfgs_W7cascP
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo;
      fi
    - test "${_status}" == "ED"

CANO_dcmip163r100_gnu:
  stage: run_configs_gnu
  dependencies:
  - build_gnu-12.1.0
  when: always
  only:
  - tags
  allow_failure: true
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_gnu_12
    - cd $GEM_WORK
    - CFG=CANO_cfgs_dcmip163r100
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo;
      fi
    - test "${_status}" == "ED"

CANO_wil7_gnu:
  stage: run_configs_gnu
  dependencies:
  - build_gnu-12.1.0
  when: always
  only:
  - tags
  allow_failure: true
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_gnu_12
    - cd $GEM_WORK
    - CFG=CANO_cfgs_wil7
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo;
      fi
    - test "${_status}" == "ED"

GEM_cfgs_gnu:
  stage: run_configs_gnu
  dependencies:
  - build_gnu-12.1.0
  when: always
  only:
  - tags
  allow_failure: true
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_gnu_12
    - cd $GEM_WORK
    - CFG=GEM_cfgs
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo;
      fi
    - test "${_status}" == "ED"

GEM_GY_FISL_P_gnu:
  stage: run_configs_gnu
  dependencies:
  - build_gnu-12.1.0
  when: always
  only:
  - tags
  allow_failure: true
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_gnu_12
    - cd $GEM_WORK
    - CFG=GEM_cfgs_GY_FISL_P
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo;
      fi
    - test "${_status}" == "ED"

GEM_GY_FISL_H_gnu:
  stage: run_configs_gnu
  dependencies:
  - build_gnu-12.1.0
  when: always
  only:
  - tags
  allow_failure: true
  script:
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_gnu_12
    - cd $GEM_WORK
    - CFG=GEM_cfgs_GY_FISL_H
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo;
      fi
    - test "${_status}" == "ED"

GEM_LU_FISL_H_gnu:
  stage: run_configs_gnu
  dependencies:
  - build_gnu-12.1.0
  when: always
  only:
  - tags
  allow_failure: true
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_gnu_12
    - cd $GEM_WORK
    - CFG=GEM_cfgs_LU_FISL_H
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo;
      fi
    - test "${_status}" == "ED"

GEM_LU_OFFC_gnu:
  stage: run_configs_gnu
  dependencies:
  - build_gnu-12.1.0
  when: always
  only:
  - tags
  allow_failure: true
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_gnu_12
    - cd $GEM_WORK
    - CFG=GEM_cfgs_LU_OFFC
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo;
      fi
    - test "${_status}" == "ED"

PTOPO_GYH_gnu:
  stage: run_configs_gnu
  dependencies:
  - build_gnu-12.1.0
  when: always
  only:
  - tags
  allow_failure: true
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_gnu_12
    - cd $GEM_WORK
    - CFG=PTOPO_cfgs_GYH
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo;
      fi
    - test "${_status}" == "ED"

PTOPO_LUP_gnu:
  stage: run_configs_gnu
  dependencies:
  - build_gnu-12.1.0
  when: always
  only:
  - tags
  allow_failure: true
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_gnu_12
    - cd $GEM_WORK
    - CFG=PTOPO_cfgs_LUP
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo;
      fi
    - test "${_status}" == "ED"

RSTRT_GYP_gnu:
  stage: run_configs_gnu
  dependencies:
  - build_gnu-12.1.0
  when: always
  only:
  - tags
  allow_failure: true
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_gnu_12
    - cd $GEM_WORK
    - CFG=RSTRT_cfgs_GYP
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runprep.sh -dircfg ./configurations/$CFG
    - if [ "${_status}" == "ED" ]; then
      _status=ABORT;
      . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo;
      fi
    - test "${_status}" == "ED"

THEO_bubbleG_gnu:
  stage: run_configs_gnu
  dependencies:
  - build_gnu-12.1.0
  when: always
  only:
  - tags
  allow_failure: true
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_gnu_12
    - cd $GEM_WORK
    - CFG=THEO_cfgs_bubbleG
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo;
    - test "${_status}" == "ED"

THEO_schar_gnu:
  stage: run_configs_gnu
  dependencies:
  - build_gnu-12.1.0
  when: always
  only:
  - tags
  allow_failure: true
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_gnu_12
    - cd $GEM_WORK
    - CFG=THEO_cfgs_schar
    - . ./configurations/$CFG/cfg_0000/configexp.cfg
    - _status=ABORT
    - . r.call.dot runmod.sh -dircfg ./configurations/$CFG -ptopo $GEMTEST_ptopo;
    - test "${_status}" == "ED"
