variables:
  ORD_SOUMET_SHELL: "/bin/bash"
  ORD_SOUMET_CPUS: "4"
  ORD_SOUMET_W: "30"
  ORD_SOUMET_M: "8G"
  ORD_SOUMET_TMPFS: "1G"
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

before_script:
  - export CLICOLOR_FORCE=1

# U2 GNU 9.3.0 with oneAPI
build_gnu-9.3.0:
  stage: build
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_gnu
    - . ./.initial_setup
    - make cmake
    - make -j `nproc`

# U2 Intel 2022
build_intel:
  stage: build
  when: always
  script:
    - set +e
    - . ~/ci-env/latest/profile.sh
    - . ./.eccc_setup_intel
    - . ./.initial_setup
    - make cmake
    - make -j `nproc`
